### ISSUE TITLE
unit tests fails on ConfigNotFound exception 

### ISSUE THREAD

**Issue by mbukatov** [Tendrl/ceph_integration#146]
All unit tests on master branch fails on ConfigNotFound error, see example of full report of 1st issue which failed in this way:

```
______ ERROR collecting tendrl/ceph_integration/tests/test_ceph_bridge.py ______
tendrl/ceph_integration/tests/test_ceph_bridge.py:10: in <module>
    from tendrl.ceph_integration.tests import base
tendrl/ceph_integration/__init__.py:55: in <module>
    CephIntegrationNS()
tendrl/ceph_integration/__init__.py:53: in __init__
    super(CephIntegrationNS, self).__init__()
.tox/py27-cover-master/lib/python2.7/site-packages/tendrl/commons/__init__.py:29: in __init__
    self.config = ns_obj.objects.Config()
tendrl/ceph_integration/objects/config/__init__.py:14: in __init__
    "/etc/tendrl/ceph-integration/ceph-integration.conf.yaml")
.tox/py27-cover-master/lib/python2.7/site-packages/tendrl/commons/config.py:21: in load_config
    raise err
E   ConfigNotFound: Configuration for module: ceph-integration not found at /etc/tendrl/ceph-integration/ceph-integration.conf.yaml
------------------------------- Captured stderr --------------------------------
No handlers could be found for logger "tendrl.commons.config"
```

The root cause of this problem seems to be wrong design of configuration loading. When I just try to import tendrl.ceph_integration module, the import fails on ConfigNotFound exception:

```
$ python
Python 2.7.13 (default, Jan 12 2017, 17:59:37) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tendrl
>>> import tendrl.ceph_integration
No handlers could be found for logger "tendrl.commons.config"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/martin/projects/tendrl.org/tendrl-ceph-integration/tendrl/ceph_integration/__init__.py", line 55, in <module>
    CephIntegrationNS()
  File "/home/martin/projects/tendrl.org/tendrl-ceph-integration/tendrl/ceph_integration/__init__.py", line 53, in __init__
    super(CephIntegrationNS, self).__init__()
  File "/home/martin/projects/tendrl.org/tendrl-ceph-integration/.env/lib/python2.7/site-packages/tendrl/commons/__init__.py", line 29, in __init__
    self.config = ns_obj.objects.Config()
  File "/home/martin/projects/tendrl.org/tendrl-ceph-integration/tendrl/ceph_integration/objects/config/__init__.py", line 14, in __init__
    "/etc/tendrl/ceph-integration/ceph-integration.conf.yaml")
  File "/home/martin/projects/tendrl.org/tendrl-ceph-integration/.env/lib/python2.7/site-packages/tendrl/commons/config.py", line 21, in load_config
    raise err
tendrl.commons.config.ConfigNotFound: Configuration for module: ceph-integration not found at /etc/tendrl/ceph-integration/ceph-integration.conf.yaml
>>> 
```

This is not a good design, because it makes debugging, unit testing and maintenance in the long term much harder.

**Comment by mbukatov** [comment]
The same issue is present in tendrl-node-agent as well: https://github.com/Tendrl/node-agent/issues/245

**Comment by r0h4n** [comment]
Unit tests written for tendrl services will have to mock all the NS.$object  (eg: NS.config, NS.tendrl_context etc), this will allow unit tests to run without failures from actual file ops or etcd ops.

Regarding the current issue, tendrl services are meant to fail if no config yaml is found, and that is intended because tendrl requires central store at any given time which is provided via config details
